// Generated by CoffeeScript 1.8.0
(function() {
  var TodoCtrl, app;

  app = angular.module('todoApp', []);

  app.controller('TodoCtrl', TodoCtrl = (function() {
    function TodoCtrl() {}

    TodoCtrl.prototype.list = [
      {
        text: "learn coffescript",
        done: false
      }, {
        text: "learn angular",
        done: true
      }
    ];

    TodoCtrl.prototype.addTodo = function() {
      this.list.push({
        text: this.input,
        done: false
      });
      return this.input = '';
    };

    TodoCtrl.prototype.remaining = function() {
      var count, todo, _i, _len, _ref;
      count = 0;
      _ref = this.list;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        todo = _ref[_i];
        count += todo.done ? 0 : 1;
      }
      return count;
    };

    TodoCtrl.prototype.archive = function() {
      var oldList, todo, _i, _len, _results;
      oldList = this.list;
      this.list = [];
      _results = [];
      for (_i = 0, _len = oldList.length; _i < _len; _i++) {
        todo = oldList[_i];
        if (!todo.done) {
          _results.push(this.list.push(todo));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return TodoCtrl;

  })());

}).call(this);
